#!/bin/sh

cd $1
export TESTS_ROOT=`pwd`
export TESTS_TMP="/tmp/nginx-js-tests"
export NGX_OBJS=$2
export NGINX="$NGX_OBJS/nginx"

echo "TESTS_ROOT=$TESTS_ROOT"

mkdir -p $TESTS_TMP

for f in tests/*
do
	export TEST_DIR="$TESTS_ROOT/$f"
	cd $f
	if [ -x ./test.pl ]; then
		echo "running $f"
		./test.pl
	fi
	cd $TESTS_ROOT
done

