#!/usr/bin/perl -w

use strict;
use Test;
use nginx;
use LWP::UserAgent;

plan tests => 2;

my $nginx = Nginx->new;
$nginx->run;


my $ua = LWP::UserAgent->new;
$ua->agent("LWP");


my $req = HTTP::Request->new(GET => 'http://localhost:9090/test');
my $res = $ua->request($req);

ok($res->is_success);
ok($res->content, "js works!");


$nginx->stop();

